import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ScrollToTop from "@/components/Common/ScrollUp";
import "../styles/index.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <head />
      <body
        className={`bg-[#FCFCFC] dark:bg-black ${inter.className}`}
      >
        <Providers>
          {children}
          <ScrollToTop />
        </Providers>
      </body>
    </html>
  );
}
